# .streamlit/config.toml
[theme]
primaryColor = "#6f4f28"  # Warm Brown
backgroundColor = "#dcd6c7"  # Pale Taupe
secondaryBackgroundColor = "#f5f1e8"  # White
textColor = "#000"  # Black
font = "robonto"
